#############################################################################
# Makefile for building: bin/openhantek
# Generated by qmake (2.01a) (Qt 4.8.7) on: Wed Dec 30 01:11:08 2020
# Project:  OpenHantek.pro
# Template: app
# Command: /usr/bin/qmake-qt4 PREFIX=/usr -o Makefile OpenHantek.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DLIBUSB_VERSION=1 -DQMAKE_TRANSLATIONS_PATH=\"/usr/share/apps/openhantek/translations\" -DOS_UNIX -DVERSION=\"0.2.0\" -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -iquote /mnt/codebase/archlinux/aur/openhantek/src/openhantek/src -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/include/libusb -I/usr/X11R6/include -Ibuild/moc
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lfftw3 -lusb-1.0 -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/colorbox.cpp \
		src/configdialog.cpp \
		src/configpages.cpp \
		src/dataanalyzer.cpp \
		src/dockwindows.cpp \
		src/dsocontrol.cpp \
		src/dsowidget.cpp \
		src/exporter.cpp \
		src/glgenerator.cpp \
		src/glscope.cpp \
		src/helper.cpp \
		src/levelslider.cpp \
		src/main.cpp \
		src/openhantek.cpp \
		src/settings.cpp \
		src/hantek/control.cpp \
		src/hantek/device.cpp \
		src/hantek/types.cpp \
		src/dso.cpp build/moc/moc_colorbox.cpp \
		build/moc/moc_configdialog.cpp \
		build/moc/moc_configpages.cpp \
		build/moc/moc_dataanalyzer.cpp \
		build/moc/moc_dockwindows.cpp \
		build/moc/moc_dsocontrol.cpp \
		build/moc/moc_dsowidget.cpp \
		build/moc/moc_exporter.cpp \
		build/moc/moc_glscope.cpp \
		build/moc/moc_glgenerator.cpp \
		build/moc/moc_levelslider.cpp \
		build/moc/moc_openhantek.cpp \
		build/moc/moc_settings.cpp \
		build/moc/moc_control.cpp \
		build/moc/moc_device.cpp \
		qrc_application.cpp \
		qrc_configdialog.cpp
OBJECTS       = build/obj/colorbox.o \
		build/obj/configdialog.o \
		build/obj/configpages.o \
		build/obj/dataanalyzer.o \
		build/obj/dockwindows.o \
		build/obj/dsocontrol.o \
		build/obj/dsowidget.o \
		build/obj/exporter.o \
		build/obj/glgenerator.o \
		build/obj/glscope.o \
		build/obj/helper.o \
		build/obj/levelslider.o \
		build/obj/main.o \
		build/obj/openhantek.o \
		build/obj/settings.o \
		build/obj/control.o \
		build/obj/device.o \
		build/obj/types.o \
		build/obj/dso.o \
		build/obj/moc_colorbox.o \
		build/obj/moc_configdialog.o \
		build/obj/moc_configpages.o \
		build/obj/moc_dataanalyzer.o \
		build/obj/moc_dockwindows.o \
		build/obj/moc_dsocontrol.o \
		build/obj/moc_dsowidget.o \
		build/obj/moc_exporter.o \
		build/obj/moc_glscope.o \
		build/obj/moc_glgenerator.o \
		build/obj/moc_levelslider.o \
		build/obj/moc_openhantek.o \
		build/obj/moc_settings.o \
		build/obj/moc_control.o \
		build/obj/moc_device.o \
		build/obj/qrc_application.o \
		build/obj/qrc_configdialog.o
DIST          = ChangeLog \
		COPYING \
		INSTALL \
		res/images/*.png \
		res/images/*.icns \
		res/images/*.svg \
		translations/*.qm \
		translations/*.ts \
		Doxyfile \
		mainpage.dox \
		roadmap.dox \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		OpenHantek.pro
QMAKE_TARGET  = openhantek
DESTDIR       = bin/
TARGET        = bin/openhantek

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OpenHantek.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) PREFIX=/usr -o Makefile OpenHantek.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) PREFIX=/usr -o Makefile OpenHantek.pro

dist: 
	@$(CHK_DIR_EXISTS) build/obj/openhantek0.2.0 || $(MKDIR) build/obj/openhantek0.2.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/obj/openhantek0.2.0/ && $(COPY_FILE) --parents src/colorbox.h src/configdialog.h src/configpages.h src/dataanalyzer.h src/dockwindows.h src/dsocontrol.h src/dsowidget.h src/exporter.h src/glscope.h src/glgenerator.h src/helper.h src/levelslider.h src/openhantek.h src/settings.h src/hantek/control.h src/hantek/device.h src/hantek/types.h src/dso.h build/obj/openhantek0.2.0/ && $(COPY_FILE) --parents res/application.qrc res/configdialog.qrc build/obj/openhantek0.2.0/ && $(COPY_FILE) --parents src/colorbox.cpp src/configdialog.cpp src/configpages.cpp src/dataanalyzer.cpp src/dockwindows.cpp src/dsocontrol.cpp src/dsowidget.cpp src/exporter.cpp src/glgenerator.cpp src/glscope.cpp src/helper.cpp src/levelslider.cpp src/main.cpp src/openhantek.cpp src/settings.cpp src/hantek/control.cpp src/hantek/device.cpp src/hantek/types.cpp src/dso.cpp build/obj/openhantek0.2.0/ && $(COPY_FILE) --parents translations/openhantek_de.ts build/obj/openhantek0.2.0/ && (cd `dirname build/obj/openhantek0.2.0` && $(TAR) openhantek0.2.0.tar openhantek0.2.0 && $(COMPRESS) openhantek0.2.0.tar) && $(MOVE) `dirname build/obj/openhantek0.2.0`/openhantek0.2.0.tar.gz . && $(DEL_FILE) -r build/obj/openhantek0.2.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


doc: src/colorbox.cpp src/configdialog.cpp src/configpages.cpp src/dataanalyzer.cpp src/dockwindows.cpp src/dsocontrol.cpp src/dsowidget.cpp src/exporter.cpp src/glgenerator.cpp src/glscope.cpp src/helper.cpp src/levelslider.cpp src/main.cpp src/openhantek.cpp src/settings.cpp src/hantek/control.cpp src/hantek/device.cpp src/hantek/types.cpp src/dso.cpp src/colorbox.h src/configdialog.h src/configpages.h src/dataanalyzer.h src/dockwindows.h src/dsocontrol.h src/dsowidget.h src/exporter.h src/glscope.h src/glgenerator.h src/helper.h src/levelslider.h src/openhantek.h src/settings.h src/hantek/control.h src/hantek/device.h src/hantek/types.h src/dso.h Doxyfile mainpage.dox roadmap.dox
	rm -r doc/; env DEFINES="LIBUSB_VERSION=1 QMAKE_TRANSLATIONS_PATH=\"/usr/share/apps/openhantek/translations\" OS_UNIX VERSION=\"0.2.0\"" doxygen Doxyfile

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc/moc_colorbox.cpp build/moc/moc_configdialog.cpp build/moc/moc_configpages.cpp build/moc/moc_dataanalyzer.cpp build/moc/moc_dockwindows.cpp build/moc/moc_dsocontrol.cpp build/moc/moc_dsowidget.cpp build/moc/moc_exporter.cpp build/moc/moc_glscope.cpp build/moc/moc_glgenerator.cpp build/moc/moc_levelslider.cpp build/moc/moc_openhantek.cpp build/moc/moc_settings.cpp build/moc/moc_control.cpp build/moc/moc_device.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_colorbox.cpp build/moc/moc_configdialog.cpp build/moc/moc_configpages.cpp build/moc/moc_dataanalyzer.cpp build/moc/moc_dockwindows.cpp build/moc/moc_dsocontrol.cpp build/moc/moc_dsowidget.cpp build/moc/moc_exporter.cpp build/moc/moc_glscope.cpp build/moc/moc_glgenerator.cpp build/moc/moc_levelslider.cpp build/moc/moc_openhantek.cpp build/moc/moc_settings.cpp build/moc/moc_control.cpp build/moc/moc_device.cpp
build/moc/moc_colorbox.cpp: src/colorbox.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/colorbox.h -o build/moc/moc_colorbox.cpp

build/moc/moc_configdialog.cpp: src/configdialog.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/configdialog.h -o build/moc/moc_configdialog.cpp

build/moc/moc_configpages.cpp: src/dsowidget.h \
		src/dockwindows.h \
		src/dso.h \
		src/settings.h \
		src/glscope.h \
		src/glgenerator.h \
		src/levelslider.h \
		src/configpages.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/configpages.h -o build/moc/moc_configpages.cpp

build/moc/moc_dataanalyzer.cpp: src/dso.h \
		src/helper.h \
		src/dataanalyzer.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/dataanalyzer.h -o build/moc/moc_dataanalyzer.cpp

build/moc/moc_dockwindows.cpp: src/dso.h \
		src/settings.h \
		src/dockwindows.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/dockwindows.h -o build/moc/moc_dockwindows.cpp

build/moc/moc_dsocontrol.cpp: src/dso.h \
		src/helper.h \
		src/dsocontrol.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/dsocontrol.h -o build/moc/moc_dsocontrol.cpp

build/moc/moc_dsowidget.cpp: src/dockwindows.h \
		src/dso.h \
		src/settings.h \
		src/glscope.h \
		src/glgenerator.h \
		src/levelslider.h \
		src/dsowidget.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/dsowidget.h -o build/moc/moc_dsowidget.cpp

build/moc/moc_exporter.cpp: src/exporter.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/exporter.h -o build/moc/moc_exporter.cpp

build/moc/moc_glscope.cpp: src/glgenerator.h \
		src/dso.h \
		src/glscope.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/glscope.h -o build/moc/moc_glscope.cpp

build/moc/moc_glgenerator.cpp: src/dso.h \
		src/glgenerator.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/glgenerator.h -o build/moc/moc_glgenerator.cpp

build/moc/moc_levelslider.cpp: src/levelslider.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/levelslider.h -o build/moc/moc_levelslider.cpp

build/moc/moc_openhantek.cpp: src/openhantek.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/openhantek.h -o build/moc/moc_openhantek.cpp

build/moc/moc_settings.cpp: src/dso.h \
		src/settings.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/settings.h -o build/moc/moc_settings.cpp

build/moc/moc_control.cpp: src/hantek/control.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/hantek/control.h -o build/moc/moc_control.cpp

build/moc/moc_device.cpp: src/hantek/device.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/hantek/device.h -o build/moc/moc_device.cpp

compiler_rcc_make_all: qrc_application.cpp qrc_configdialog.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp qrc_configdialog.cpp
qrc_application.cpp: res/application.qrc \
		res/images/openhantek.png \
		res/images/actions/print.png \
		res/images/actions/save-as.png \
		res/images/actions/stop.png \
		res/images/actions/export-as.png \
		res/images/actions/zoom.png \
		res/images/actions/start.png \
		res/images/actions/save.png \
		res/images/actions/digitalphosphor.png \
		res/images/actions/open.png
	/usr/lib/qt4/bin/rcc -name application res/application.qrc -o qrc_application.cpp

qrc_configdialog.cpp: res/configdialog.qrc \
		res/images/config/analysis.png \
		res/images/config/files.png \
		res/images/config/colors.png \
		res/images/config/scope.png
	/usr/lib/qt4/bin/rcc -name configdialog res/configdialog.qrc -o qrc_configdialog.cpp

compiler_image_collection_make_all: build/ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) build/ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

build/obj/colorbox.o: src/colorbox.cpp src/colorbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/colorbox.o src/colorbox.cpp

build/obj/configdialog.o: src/configdialog.cpp src/configdialog.h \
		src/configpages.h \
		src/dsowidget.h \
		src/dockwindows.h \
		src/dso.h \
		src/settings.h \
		src/glscope.h \
		src/glgenerator.h \
		src/levelslider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/configdialog.o src/configdialog.cpp

build/obj/configpages.o: src/configpages.cpp src/configpages.h \
		src/dsowidget.h \
		src/dockwindows.h \
		src/dso.h \
		src/settings.h \
		src/glscope.h \
		src/glgenerator.h \
		src/levelslider.h \
		src/colorbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/configpages.o src/configpages.cpp

build/obj/dataanalyzer.o: src/dataanalyzer.cpp src/dataanalyzer.h \
		src/dso.h \
		src/helper.h \
		src/glscope.h \
		src/glgenerator.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dataanalyzer.o src/dataanalyzer.cpp

build/obj/dockwindows.o: src/dockwindows.cpp src/dockwindows.h \
		src/dso.h \
		src/settings.h \
		src/helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dockwindows.o src/dockwindows.cpp

build/obj/dsocontrol.o: src/dsocontrol.cpp src/dsocontrol.h \
		src/dso.h \
		src/helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dsocontrol.o src/dsocontrol.cpp

build/obj/dsowidget.o: src/dsowidget.cpp src/dsowidget.h \
		src/dockwindows.h \
		src/dso.h \
		src/settings.h \
		src/glscope.h \
		src/glgenerator.h \
		src/levelslider.h \
		src/dataanalyzer.h \
		src/helper.h \
		src/exporter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dsowidget.o src/dsowidget.cpp

build/obj/exporter.o: src/exporter.cpp src/exporter.h \
		src/dataanalyzer.h \
		src/dso.h \
		src/helper.h \
		src/glgenerator.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/exporter.o src/exporter.cpp

build/obj/glgenerator.o: src/glgenerator.cpp src/glgenerator.h \
		src/dso.h \
		src/dataanalyzer.h \
		src/helper.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/glgenerator.o src/glgenerator.cpp

build/obj/glscope.o: src/glscope.cpp src/glscope.h \
		src/glgenerator.h \
		src/dso.h \
		src/dataanalyzer.h \
		src/helper.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/glscope.o src/glscope.cpp

build/obj/helper.o: src/helper.cpp src/helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/helper.o src/helper.cpp

build/obj/levelslider.o: src/levelslider.cpp src/levelslider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/levelslider.o src/levelslider.cpp

build/obj/main.o: src/main.cpp src/openhantek.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o src/main.cpp

build/obj/openhantek.o: src/openhantek.cpp src/openhantek.h \
		src/configdialog.h \
		src/dataanalyzer.h \
		src/dso.h \
		src/helper.h \
		src/dockwindows.h \
		src/settings.h \
		src/dsocontrol.h \
		src/dsowidget.h \
		src/glscope.h \
		src/glgenerator.h \
		src/levelslider.h \
		src/hantek/control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/openhantek.o src/openhantek.cpp

build/obj/settings.o: src/settings.cpp src/settings.h \
		src/dso.h \
		src/dsowidget.h \
		src/dockwindows.h \
		src/glscope.h \
		src/glgenerator.h \
		src/levelslider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/settings.o src/settings.cpp

build/obj/control.o: src/hantek/control.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/control.o src/hantek/control.cpp

build/obj/device.o: src/hantek/device.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/device.o src/hantek/device.cpp

build/obj/types.o: src/hantek/types.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/types.o src/hantek/types.cpp

build/obj/dso.o: src/dso.cpp src/dso.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dso.o src/dso.cpp

build/obj/moc_colorbox.o: build/moc/moc_colorbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_colorbox.o build/moc/moc_colorbox.cpp

build/obj/moc_configdialog.o: build/moc/moc_configdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_configdialog.o build/moc/moc_configdialog.cpp

build/obj/moc_configpages.o: build/moc/moc_configpages.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_configpages.o build/moc/moc_configpages.cpp

build/obj/moc_dataanalyzer.o: build/moc/moc_dataanalyzer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dataanalyzer.o build/moc/moc_dataanalyzer.cpp

build/obj/moc_dockwindows.o: build/moc/moc_dockwindows.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dockwindows.o build/moc/moc_dockwindows.cpp

build/obj/moc_dsocontrol.o: build/moc/moc_dsocontrol.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dsocontrol.o build/moc/moc_dsocontrol.cpp

build/obj/moc_dsowidget.o: build/moc/moc_dsowidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dsowidget.o build/moc/moc_dsowidget.cpp

build/obj/moc_exporter.o: build/moc/moc_exporter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_exporter.o build/moc/moc_exporter.cpp

build/obj/moc_glscope.o: build/moc/moc_glscope.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_glscope.o build/moc/moc_glscope.cpp

build/obj/moc_glgenerator.o: build/moc/moc_glgenerator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_glgenerator.o build/moc/moc_glgenerator.cpp

build/obj/moc_levelslider.o: build/moc/moc_levelslider.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_levelslider.o build/moc/moc_levelslider.cpp

build/obj/moc_openhantek.o: build/moc/moc_openhantek.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_openhantek.o build/moc/moc_openhantek.cpp

build/obj/moc_settings.o: build/moc/moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_settings.o build/moc/moc_settings.cpp

build/obj/moc_control.o: build/moc/moc_control.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_control.o build/moc/moc_control.cpp

build/obj/moc_device.o: build/moc/moc_device.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_device.o build/moc/moc_device.cpp

build/obj/qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/qrc_application.o qrc_application.cpp

build/obj/qrc_configdialog.o: qrc_configdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/qrc_configdialog.o qrc_configdialog.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "bin/$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_translations: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/apps/openhantek/translations/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/apps/openhantek/translations/ 
	-$(INSTALL_FILE) /mnt/codebase/archlinux/aur/openhantek/src/openhantek/translations/openhantek_de.qm $(INSTALL_ROOT)/usr/share/apps/openhantek/translations/


uninstall_translations:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/apps/openhantek/translations/openhantek_de.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/apps/openhantek/translations/ 


install:  install_target install_translations  FORCE

uninstall: uninstall_target uninstall_translations   FORCE

FORCE:

